TASK-357: Add unsaved notifications to all update and create forms
opencb/jsorolla pull request #458
Opened 2022-03-31 07:47 UTC by Rodielm

Display a warning message about unsaved data when the user creates or updates information.

2022-03-31 07:47 UTC, Rodielm commented
Task linked: [TASK-357 Add unsaved notifications to all update and create forms](https://app.clickup.com/t/36631768/TASK-357)

2022-05-18 11:53 UTC, jmjuanes requested changes

2022-05-18 11:53 UTC, jmjuanes commented on src/webcomponents/clinical/clinical-analysis-create.js
> +                            title: "",
Please remove the `title` field if is not used.

2022-05-18 11:53 UTC, jmjuanes commented on src/webcomponents/sample/sample-update.js
> +                                    .source=${source}
Please undo this change, attributes should be always wrapped in double quotes.

2022-05-18 11:53 UTC, jmjuanes commented on src/webcomponents/study/ontology-term-annotation/ontology-term-annotation-update.js
> +                .updateParams=${this.data?.updateParams}
Please wrap this attribute value in double quotes.

2022-05-18 11:53 UTC, jmjuanes commented on src/webcomponents/study/status/status-update.js
> +            console.log("update status ...");
Please remove this `console.log` line.

2022-05-18 13:31 UTC, jmjuanes approved these changes

2022-05-18 15:44 UTC, imedina approved these changes

2022-05-18 15:44 UTC, merged