Task 517: Replace EBI Ontology (GO/HPO) calls with CellBase REST API
opencb/jsorolla pull request #459
Opened 2022-04-01 12:30 UTC by Rodielm

2022-04-01 12:30 UTC, imedina commented
Task linked: [TASK-517 Replace EBI Ontology (GO/HPO) calls with CellBase REST API](https://app.clickup.com/t/36631768/TASK-517)

2022-04-06 01:30 UTC, imedina commented on src/webcomponents/commons/filters/go-accessions-filter.js
>          this._prefix = "gaf-" + UtilsNew.randomString(6) + "_";
I would remove "gaf-" prefix aqnd increase string to 8 charts

2022-04-06 08:46 UTC, jmjuanes requested changes

2022-04-06 08:46 UTC, jmjuanes commented on src/webcomponents/commons/filters/hpo-accessions-filter.js
> +        this._config = {...this.getDefaultConfig()};
The `this.getDefaultConfig` is returning a new object, so using the `{... }` in this case is redundant. 

You can just use `this._config = this.getDefaultConfig();` :wink:.

2022-04-06 08:46 UTC, jmjuanes commented on src/webcomponents/commons/filters/ontology-autocomplete-filter.js
> +    getDefaultConfig() {
Please move `getDefaultConfig()` to the last method of the class.

2022-04-06 08:46 UTC, jmjuanes commented on src/webcomponents/commons/variant-modal-ontology.js
>          };
I think this should be moved to `getDefaultConfig`.

2022-04-06 08:46 UTC, jmjuanes commented on src/webcomponents/commons/variant-modal-ontology.js
>      getDefaultConfig() {
Please move `getDefaultConfig` to the end of the class.

2022-04-06 08:46 UTC, jmjuanes commented on src/webcomponents/commons/variant-modal-ontology.js
> +                                            <button type="button" class="btn btn-default btn-small" @click="${() => this.addTerm(this.selectedItem.obo_id)}">Add Term</button>
I think this part will be more readable if you put the child elements in a new line. For example:

```html
<li class="list-group-item">
    <strong>Name: </strong>${this.selectedItem.name}
</li>
```

2022-04-06 08:46 UTC, jmjuanes commented on src/webcomponents/commons/filters/ontology-autocomplete-filter.js
> +        };
The right place for this configuration should be in `getDefaultConfig`.

Also, as I see this is only used in line 85 so maybe you do not need to declare it as a variable of the class.

2022-04-06 08:46 UTC, jmjuanes commented on src/webcomponents/commons/filters/go-accessions-filter.js
> +        this._config = {...this.getDefaultConfig()};
This could be simplified as `this._config = this.getDefaultConfig();` (see my comment below).

2022-04-06 08:46 UTC, jmjuanes commented on src/webcomponents/commons/filters/go-accessions-filter.js
> +        this.ontologyFilter = "GO";
As I see neither `this.ontologyTerm` and `this.ontologyFilter` are in use in the class. I would suggest removing them.

2022-04-07 09:21 UTC, jmjuanes requested changes

2022-04-07 09:21 UTC, jmjuanes commented on src/webcomponents/commons/filters/go-accessions-filter.js
> +    openModal(_e) {
Instead of adding an underscore character to the event argument, I suggest removing the argument, as you are not using it :)

2022-04-07 09:21 UTC, jmjuanes commented on src/webcomponents/commons/filters/hpo-accessions-filter.js
>      _init() {
As in `go-accessions-filter.js` you made the `_init` method private, I would suggest doing the same there.

2022-04-07 09:21 UTC, jmjuanes commented on src/webcomponents/commons/filters/hpo-accessions-filter.js
> +    openModal(_e) {
Same, I would suggest removing the event argument.

2022-04-07 09:21 UTC, jmjuanes commented on src/webcomponents/commons/filters/ontology-autocomplete-filter.js
> +    }
I think you do not need the constructor in this case :wink:

2022-04-07 09:21 UTC, jmjuanes commented on src/webcomponents/commons/variant-modal-ontology.js
> +
Please remove this extra line :)

2022-04-07 09:56 UTC, jmjuanes approved these changes
All looks good, thanks @Rodielm :smile:

2022-04-07 10:00 UTC, merged