TASK-2255 - The disorder filter splits the disorder.name strings by commas
opencb/jsorolla pull request #695
Opened 2022-11-08 12:36 UTC by Rodielm

This PR allows using regex as separator for select-token-filter

2022-11-08 12:36 UTC, Rodielm commented
Task linked: [TASK-2255 The disorder filter splits the disorder.name strings by commas](https://app.clickup.com/t/36631768/TASK-2255)

2022-11-11 09:49 UTC, Rodielm commented
> where is the regex expression?

Resolved!

2022-11-11 17:33 UTC, gpveronica requested changes
Small fixes: 
(1) Fix the regex
(2) Move it to a static function in UtilsNews

2022-11-23 09:40 UTC, gpveronica approved these changes

2022-11-29 11:31 UTC, merged