TASK-2549 - Role in Cancer and modeOfInheritance changes in Panel data model
opencb/jsorolla pull request #726
Opened 2023-02-10 16:38 UTC by gpveronica

This PR solves the create/update/view of multiple roles in cancer/modes of inheritance

2023-02-10 16:38 UTC, gpveronica commented
Task linked: [TASK-2549 Role in Cancer and modeOfInheritance changes in Panel data model](https://app.clickup.com/t/36631768/TASK-2549)

2023-02-10 17:22 UTC, jmjuanes requested changes

2023-02-10 17:22 UTC, jmjuanes commented on src/webcomponents/commons/forms/data-form.js
> +                        // }
Please could you remove this commented code?

2023-02-10 17:22 UTC, jmjuanes commented on src/webcomponents/commons/forms/data-form.js
> +                        // };
Please could you remove this commented code?

2023-02-10 17:36 UTC, jmjuanes approved these changes

2023-02-17 14:33 UTC, Rodielm approved these changes

2023-02-17 14:35 UTC, imedina approved these changes

2023-02-17 14:35 UTC, imedina approved these changes

2023-02-17 14:36 UTC, merged