TASK-3892 - Unable to add comments to Review Variants in sample variant browser
opencb/jsorolla pull request #756
Opened 2023-04-11 16:06 UTC by gpveronica

This PR solves the problem of adding comments to the clinical interpretation variant review

2023-04-11 16:06 UTC, gpveronica commented
Task linked: [TASK-3892 Unable to add comments to Review Variants in sample variant browser](https://app.clickup.com/t/36631768/TASK-3892)

2023-04-11 16:28 UTC, jmjuanes requested changes

2023-04-11 16:28 UTC, jmjuanes commented on src/webcomponents/clinical/interpretation/clinical-interpretation-variant-review.js
> +                                return html`
Please fix indentation of the returned HTML.

2023-04-11 16:28 UTC, jmjuanes commented on src/webcomponents/clinical/interpretation/clinical-interpretation-variant-review.js
> +
Please remove this empty line

2023-04-12 08:45 UTC, jmjuanes approved these changes

2023-05-03 12:31 UTC, jmjuanes approved these changes

2023-05-03 12:34 UTC, merged