TASK-4281
opencb/jsorolla pull request #772
Opened 2023-05-17 07:51 UTC by juanfeSanahuja

TASK-4281 - Improvements cicd

2023-05-17 07:51 UTC, juanfeSanahuja commented
Task linked: [TASK-4281 Improvements CI/CD jsorolla](https://app.clickup.com/t/36631768/TASK-4281)

2023-05-17 12:24 UTC, juanrizetta requested changes

2023-05-17 12:24 UTC, juanrizetta commented on .github/workflows/build-jsorolla-workflow.yml
> +      - uses: actions/setup-node@v3
this step seems duplicated

2023-05-17 13:05 UTC, imedina approved these changes

2023-05-18 10:48 UTC, juanrizetta approved these changes

2023-05-18 10:49 UTC, merged