TASK-3841 - IVA REST_APIapp for /analysis/alignment/coverage/qc/geneCoverageStats/run is missing the field "genes"
opencb/jsorolla pull request #775
Opened 2023-05-23 08:32 UTC by Rodielm

This PR fix genes field

2023-05-23 08:32 UTC, Rodielm commented
Task linked: [TASK-3841 IVA REST_APIapp for /analysis/alignment/coverage/qc/geneCoverageStats/run is missing the field "genes"](https://app.clickup.com/t/36631768/TASK-3841)

2023-05-23 10:17 UTC, jmjuanes requested changes

2023-05-23 10:17 UTC, jmjuanes commented on src/webcomponents/api/rest-endpoint.js
> +        const isListString = dataParameter => dataParameter.complex && (dataParameter.type === "List") && (dataParameter["data"] === undefined);
Please use `typeof dataParameter["data"] === "undefined"` instead.

2023-05-23 10:17 UTC, jmjuanes commented on src/webcomponents/api/rest-endpoint.js
> +                            console.log("render list<string> input");
Please remove this `console.log`.

2023-05-23 10:17 UTC, jmjuanes commented on src/webcomponents/api/rest-endpoint.js
> +
Please remove this empty line.

2023-05-23 10:17 UTC, jmjuanes commented on src/webcomponents/api/rest-endpoint.js
> +
Same, empty line.

2023-05-23 12:14 UTC, jmjuanes approved these changes

2023-06-02 12:12 UTC, jmjuanes approved these changes

2023-06-02 12:13 UTC, merged