TASK-2366 - IVA API DOC for sample, individual, cohort, family and file ACL produces wrong REST call
opencb/jsorolla pull request #776
Opened 2023-05-23 08:39 UTC by Rodielm

This PR fix duplicate study params and capture default value from select input.

2023-05-23 08:39 UTC, Rodielm commented
Task linked: [TASK-2366 IVA API DOC for sample, individual, cohort, family and file ACL produces wrong REST call](https://app.clickup.com/t/36631768/TASK-2366)

2023-05-23 09:58 UTC, jmjuanes requested changes

2023-05-23 09:58 UTC, jmjuanes commented on src/webcomponents/api/rest-endpoint.js
> +            .filter(parameter => (parameter.name === "query" && parameter.required) && this.data.param[parameter.name] === undefined)
1. Are you sure that the condition `parameter.name === "query"` is correct?
2. Please use `typeof this.data.param[parameter.name] === "undefined"` instead.

2023-06-02 10:48 UTC, jmjuanes approved these changes

2023-06-02 10:49 UTC, merged