TASK-4495 Cohort overview detailed tab samples table needs to be paginated
opencb/jsorolla pull request #807
Opened 2023-08-04 12:40 UTC by Rodielm

This PR involves the implementation of a new datatable that includes additional features such as pagination, sorting, and filtering.

2023-08-04 12:40 UTC, Rodielm commented
Task linked: [TASK-4495 Cohort overview detailed tab samples table needs to be paginated](https://app.clickup.com/t/36631768/TASK-4495)

2023-08-10 16:34 UTC, jmjuanes requested changes

2023-08-10 16:34 UTC, jmjuanes commented on src/webcomponents/cohort/cohort-view.js
> +
Please remove this.

2023-08-10 16:34 UTC, jmjuanes commented on src/webcomponents/cohort/cohort-view.js
> -                                        defaultValue: "false",
Please add a formatter for displaying `"true"` or `"false"` as strings.

2023-08-10 16:34 UTC, jmjuanes commented on src/webcomponents/individual/individual-view.js
> +                                        fomatter: value => value ?? false
Please change the returned value to string: 

```
formatter: value => value ? "true" : "false",
```

2023-08-10 16:34 UTC, jmjuanes commented on src/webcomponents/individual/individual-view.js
> +                                        formatter: value => value?.length ? html`${value.map(d => d.id).join(", ")}` : "-",
Please remove the `html` from the formatter function

2023-08-10 16:34 UTC, jmjuanes commented on src/webcomponents/user/user-projects.js
>                                      `,
Please fix indentation

2023-08-10 16:34 UTC, jmjuanes commented on src/webcomponents/variant/interpretation/variant-interpreter-qc-summary.js
> +                                        `,
Please remove the `html` from this formatter

2023-08-10 16:34 UTC, jmjuanes commented on src/webcomponents/variant/interpretation/variant-interpreter-qc-summary.js
> +                                        `,
Please remove the `html` from this formatter

2023-08-10 16:34 UTC, jmjuanes commented on src/webcomponents/variant/interpretation/variant-interpreter-qc-summary.js
> +                                        `,
Please remove the `html` from this formatter.

2023-08-10 16:34 UTC, jmjuanes commented on src/webcomponents/variant/interpretation/variant-interpreter-qc-summary.js
>                                              `,
Please remove the `html` from this formatter and fix indentation.

2023-08-10 16:34 UTC, jmjuanes commented on src/webcomponents/variant/interpretation/variant-interpreter-qc-summary.js
> +                                        `,
Please remove the `html` from this formatter.

2023-08-11 08:53 UTC, jmjuanes approved these changes

2023-08-31 07:08 UTC, merged